### ISSUE TITLE
add designspace.json

### ISSUE THREAD

**Issue by BlackFoundry** [BlackFoundryCom/robo-cjk#10]
add the file accodring to the "font infos" to the project on the repo so that one can generate the VarC VF font

**Comment by fabiocaccamo** [comment]
@BlackFoundry @GaetanBaehr do you mean the possibility to manage it via API like `fontLib.json`?

**Comment by BlackFoundry** [comment]
Please refer to this, the designspace.json is required to build the binary font:
https://github.com/BlackFoundryCom/rcjk-tools#robocjk-to-varc-vf-workflow

**Comment by fabiocaccamo** [comment]
@BlackFoundry this is not strictly-related to how API works, actually the `designspace.json` is automatically pushed but not managed by the APIs, if it must be managed with some automatism I should know the desired result.

**Comment by justvanrossum** [comment]
Can this please be resolved? I'm not sure I understand what needs to be done to make it happen.

(Gaëtan imported a new version of the hangul.rcjk project, which did contain a designspace.json file, but designspace.json didn't get imported and now no longer exists in git, making the CI fail.)

**Comment by fabiocaccamo** [comment]
This will be solved soon, in the meantime to avoid the CI failure the `designspace.json` file could be added manually to the repository.

**Comment by fabiocaccamo** [comment]
@justvanrossum @GaetanBaehr @BlackFoundry this is done.

Now `designspace.json` is imported when importing a font from the backend and exported to git when modified. It is possible to modify `designspace.json` data using the API (the local client must be updated with the [latest client version](https://github.com/BlackFoundryCom/django-robo-cjk/blob/master/robocjk/api/client.py)).

---

I'm sorry, I committed a mistake and referenced the wrong repo in the commit (I did it just for demonstrating that referencing issues cross-repositories could be confusing :) ).

I reference the commit manually here: [Added designspace support to API and client.](https://github.com/BlackFoundryCom/django-robo-cjk/commit/a6a542fd05b71da5fa8545b96c205fda4723e53c)

**Comment by justvanrossum** [comment]
All existing designspace.json files have now been replaced with empty ones. Please revert to what they were before.

**Comment by fabiocaccamo** [comment]
Were there any other `designspace.json` files besides this?: https://github.com/BlackFoundryCom/gs-cjk-rcjk/commit/923dfed9edb611a22c02a4b09ede448307338fdf

**Comment by justvanrossum** [comment]
> Were there any other designspace.json files besides this: BlackFoundryCom/gs-cjk-rcjk@923dfed ?

They were non-empty in every .rcjk project, but they were (most likely) all identical to that one.

**Comment by fabiocaccamo** [comment]
There is no need to revert changes, just need to update the font `designspace.json` data from the backend or via the api.

**Comment by justvanrossum** [comment]
Whatever you call it, please make it happen... I'm not working with the front end, and don't even have access to the projects from that side.

**Comment by fabiocaccamo** [comment]
I added them, so in the next sync designspaces will be pushed.

**Comment by justvanrossum** [comment]
Thanks! This issue should be closed (but I can't).

**Comment by fabiocaccamo** [comment]
Me neither, @BlackFoundry could you close this issue?
