### ISSUE TITLE
prettify .glif MySQL output to GIT

### ISSUE THREAD

**Issue by BlackFoundry** [BlackFoundryCom/robo-cjk#12]
the XML files should be formated nicely with proper lines and indents

**Comment by justvanrossum** [comment]
It shouldn't be "prettified": .glif should be formatted exactly as how ufoLib/glifLib saves it, otherwise we can never make changes from the git side without potentally adding format changes. The best way to do that is to build the XML with glifLib.

**Comment by fabiocaccamo** [comment]
@justvanrossum what do you mean? xml data is the same independently by how it is formatted, I think in this case the prettify is just for readable reasons, @BlackFoundry isn't it?

**Comment by justvanrossum** [comment]
If I edit a glyph with fonttools based code, and commit it to the repo, I don't want to be distracted by formatting differences. glifLib provides the canonical formatting, why not use it?

**Comment by BlackFoundry** [comment]
Yes that's the point @fabiocaccamo

**Comment by justvanrossum** [comment]
The changeover to the MySQL frontend should not have caused _any_ formatting changes whatsoever. (The case renaming of the .rcjk folders was very unfortunate also.)

**Comment by fabiocaccamo** [comment]
@justvanrossum thank you for the explanation, understood. 
Actually on server side we don't use `glifLib` at all, we manage xml using `ElementTree`.
Using `glifLib` is it possible just format an xml to obtain the desired result?

**Comment by justvanrossum** [comment]
Unfortunately it doesn't have this functionality builtin, and this is the shortest I could come up with (only lightly tested):

```python
from fontTools.pens.recordingPen import RecordingPointPen
from fontTools.ufoLib.glifLib import readGlyphFromString, writeGlyphToString


class GlyphObject:
    pass


def reformatGLIF(original):
    glyph = GlyphObject()
    recorder = RecordingPointPen()
    readGlyphFromString(original, glyph, pointPen=recorder)
    return writeGlyphToString(glyph.name, glyph, drawPointsFunc=recorder.replay)


p = 'path/to/glyph.glif'

with open(p) as f:
    original = f.read()
    new = reformatGLIF(original)
    print(new)
```

**Comment by fabiocaccamo** [comment]
@justvanrossum I'm sorry for the inconvenience, keeping data formatted identically was not in the requirements, so I thought the only important thing was that the data was not changed. Btw, now that I know it we can fix it easily. 
Thank you very much for the snippet.

**Comment by justvanrossum** [comment]
I would have thought a requirement "data was not changed" would mean "in the repo" and therefore implies to include formatting... But I'm glad this is being fixed.

**Comment by justvanrossum** [comment]
This seems to be done as well. (Again, please reference `#N` issue numbers in commits and/or PRs.)

**Comment by fabiocaccamo** [comment]
@justvanrossum yes this has been implemented. 

Unfortunately the issue has been opened on the wrong repo, so it was not possible for me to reference the issue in the commit. 

To avoid this problem in future the next issues related to backend/api should be opened on the [django-robo-cjk](https://github.com/BlackFoundryCom/django-robo-cjk) repository.

**Comment by fabiocaccamo** [comment]
@justvanrossum I also compared performance of `glifLib` vs native `xml` on 30000 iterations and there is not difference.

**Comment by justvanrossum** [comment]
Excellent. (But even if there is a difference, given the granularity of the system, I would not expect glifLib to be a bottleneck wrt. responsiveness.)
