### ISSUE TITLE
MySQL user password change

### ISSUE THREAD

**Issue by BlackFoundry** [BlackFoundryCom/robo-cjk#13]
Any user should be able to change his password

**Comment by fabiocaccamo** [comment]
@BlackFoundry this is already possible using the backend: `https://robocjk.black-foundry.com/admin/auth/user/`

It would be also possible integrate a WebView inside the plugin and load directly the password-change page build the url using the following format: `{{ host }}/admin/auth/user/{{ user.id }}/change/`

**Comment by fabiocaccamo** [comment]
@BlackFoundry this issue could be closed.
