### ISSUE TITLE
SQL commit message *should* include the username resposible of the last change

### ISSUE THREAD

**Issue by BlackFoundry** [BlackFoundryCom/robo-cjk#15]

**Comment by justvanrossum** [comment]
Or: all user names since the last commit, if there were more.

**Comment by BlackFoundry** [comment]
Just said: GIT should be the main data storage; SQL being a speedy caching frontend.
The idea is that we don't loose the benefits of GIT

**Comment by fabiocaccamo** [comment]
This can be done (it will surely slowdown the push phase a little bit).

**Comment by fabiocaccamo** [comment]
Is it ok a message like `Updated by: Jeremie Hornus, Gaetan Baher, etc...` ?

**Comment by justvanrossum** [comment]
This appears to be implemented, but I can't close the issue.

(Best to reference the issue when committing changes relating to the issue.)

**Comment by fabiocaccamo** [comment]
@justvanrossum yes this has been implemented. 

Unfortunately the issue has been opened on the wrong repo, so it was not possible for me to reference the issue in the commit. 

To avoid this problem in future the next issues related to backend/api should be opened on the [django-robo-cjk](https://github.com/BlackFoundryCom/django-robo-cjk) repository.

**Comment by justvanrossum** [comment]
You can reference other repos, too: BlackFoundryCom/django-robo-cjk#1

**Comment by fabiocaccamo** [comment]
Cool! I didn't know that, thank you very much for the tip!
