### ISSUE TITLE
Unneeded addition of lib to backup glyphs makes git history way too noisy

### ISSUE THREAD

**Issue by justvanrossum** [BlackFoundryCom/robo-cjk#26]
Of the 622 files touched in [this commit](https://github.com/BlackFoundryCom/gs-cjk-rcjk/commit/37d27c2d416048691eca21f8ecf21eab3da5c7de), 356 contain a redundant addition of lib, such as this:

![image](https://user-images.githubusercontent.com/4246121/137916755-fbad2ccb-dd58-4639-9cc8-955feff450bb.png)

This makes it much more difficult to find the relevant diffs than necessary. Can this please be addressed? I've asked for it several times already.

**Comment by justvanrossum** [comment]
Not just backup glyphs, but layer glyphs in general.

**Comment by justvanrossum** [comment]
This is still a major source of noise in the commits.

**Comment by justvanrossum** [comment]
With Fontra now also becoming a writer to the database, this becomes a new problem:
- When editing with Fontra the redundant data goes away
- When editing the same glyph in RoboCJK afterwards it comes back

**Comment by GaetanBaehr** [comment]
I pushed an update, should be fixed now

**Comment by justvanrossum** [comment]
Thanks, I'll check it out!

**Comment by justvanrossum** [comment]
I've confirmed it works, thanks!

**Comment by justvanrossum** [comment]
Fixed in https://github.com/BlackFoundryCom/robo-cjk/commit/764f8f914cf6059c403b52867b7f2dae1a68a137
