### ISSUE TITLE
Renaming a Character Glyph fails

### ISSUE THREAD

**Issue by justvanrossum** [BlackFoundryCom/robo-cjk#37]
RoboCJK renames a glyph by:
- creating a new glyph with the old data
- deleting the old glyph

The last step currently fails, because the lock cannot be acquired. After this the glyph exists twice in the database.

From the Python output window (when trying to rename `uni0065` to `e`):
```
uni0065 e
Couldn't acquire the lock for glyph uni0065
```

**Comment by GaetanBaehr** [comment]
This is fixed, I made a pull requests
